### ISSUE TITLE
Add criterion tests, to check for left and right leaning monadic and applicative expressions

### ISSUE THREAD

**Issue by andygill** [ku-fpg/remote-monad#6]

**Comment by andygill** [comment]
David - Here are some steps towards getting this done.

- [ ] Get remote-json tests, in the main repo, working. You can ignore the sub-repos.
- [ ] Clone the test, stub it out, check in.
- [ ] Get criterion fib example working as test, check in.
- [ ] Get trivial hand written monadic code tested under criterion, check in.
- [ ] Parameterize the monad code with
     * depth (number)
     * direction (left, right, balanced)
     * which construct to use; one of (`(<*>)`, `(*>)`, `(<*)`, (`>>`), (`>>=`)
- [ ] Investigate cabal support for running measurements/timings.

This should give is something good enough to see the problems with our normalization.

**Comment by roboguy13** [comment]
I'm working on timing nested binds of a given depth and comparing associating them to the left and the right, and both are on the order of 100 ns if I set the number of binds to be on the order of `1000000000000000^2` (using `Integer`). There is a consistent difference between the two ways to associate it of around 100 ns at this number of iterations (with right leaning being faster), but maybe I'm doing something wrong (or something is getting optimized out by GHC, even though I have `-O0`).

I'm using the stack example and my two tests look like this:

```
testLeftM :: Integer -> M.RemoteMonad C P Integer
testLeftM !count
  | count == 0 = pure count
  | otherwise  = push (count-1) >> pop >>= maybePush >> pop >>= testLeftM . fromJust

testRightM :: Integer -> M.RemoteMonad C P Integer
testRightM !count
  | count == 0 = pure count
  | otherwise  = push (count-1) >> (pop >>= (\mi -> maybePush mi >> (pop >>= testRightM . fromJust)))
```

**Comment by andygill** [comment]
Suggestions:

 * Try parentheses to the left explicitly. (It automatically binds to the right)
 * Also, try use just '>>='  first, as well as '>>' later

**Comment by roboguy13** [comment]
@andygill I added some explicit parentheses to the left one, but it didn't seem to make a difference (I think `>>=` might associate to the left by default though).

I replaced the `ma  >> mb` calls in both tests with `ma >>= const mb` and it seems to have consistently sped them both: left associative by around 30 ns and right associative by around 10 or 15 ns.

**Comment by roboguy13** [comment]
Okay, I noticed a major problem with my code above: I'm not actually nesting on the left in the `testLeftM` because the `testLeftM` recursive call is on the right at the end. If I change it to this:

```
testLeftM :: Integer -> M.RemoteMonad C P Integer
testLeftM !count
  | count == 0 = pure count
  | otherwise  = (((testLeftM (count-1) >>= const (push (count-1))) >>= const pop) >>= maybePush) >>= const (fmap fromJust pop)
```

then `testLeftM` is ~3 orders of magnitude slower than `testRightM` at just 100 iterations.

**Comment by roboguy13** [comment]
I put a README in the `criterion` directory describing how to run the benchmarks.
Here's a summary of what I've noticed on my computer so far, with the iteration count set to 1000:

 * Left leaning `>>=`s run about 3,000 times slower than right leaning `>>=`
 * A balanced tree of binds runs about 300 times faster than left leaning `>>=` (and, likewise, about 10 times slower than right leaning `>>=`)
 * A similar test using `>>` runs about 10,000 times slower than the right leaning `>>=` test (this was pretty surprising to me).
 * Left leaning `>>`s are slower than right leaning `>>`s, running about 4/3 times slower.
 * I made an exact translation of the `>>` tests to use tests using `ma >> ignoreArg mb` (`ignoreArg` is the same `const`. It just exists to avoid potential GHC optimizations). The right associated version of this test was about 10,000 times faster than the fastest `>>` test.
 * There is a similar speed difference between the left and right associated versions of the last test I mentioned as the other speed differences between the different associations from the other tests, with the right leaning version being faster as with the other tests.

**Comment by andygill** [comment]
Thanks! I'm not surprised by `>>`, because it is defined as

````
  m1 >> m2 = m1 *> m2
````

and `*>` is defined as

````
  Appl f   *> Appl g   = Appl (f *> g)
  Appl f   *> Bind m k = Bind (f *> m) k
  Bind m k *> r        = Bind m (\ a -> k a *> r) 
````
so we end up with applicatives with `>>`.

**Comment by roboguy13** [comment]
The slowdown for left leaning binds reminds me a lot of the article series [Free Monads for Less](http://comonad.com/reader/2011/free-monads-for-less/). `Free` had the same issue with left leaning binds being significantly less efficient than right leaning binds. I wonder if anything from the solution there can be adapted to our use case.

**Comment by andygill** [comment]
Yes, I think any solution will be along similar lines. But, as you stated today, the types do not line up in the same way they do for monads. This is what is interesting - we don't know how to solve it, but we'll figure something out that helps generate packets faster.

**Comment by andygill** [comment]
Done! Looks good.
