### ISSUE TITLE
remote-monad library on hackage doesn't allow the user to look at the modules

### ISSUE THREAD

**Issue by jtdawso** [ku-fpg/remote-monad#8]
In modules section,  you can't click on the Monad, Applicative and Packet modules to see the functions and data structures available

**Comment by RyanGlScott** [comment]
This is an unfortunate side-effect of Hackage having such a large backlog of packages to build—it'll probably take a while for the docs to appear. If you're impatient, you can use the [`neil`](http://hackage.haskell.org/package/neil) tool to upload the docs manually:

```bash
neil docs --username=<your-username-here>
```
