### ISSUE TITLE
Measure combinations of combinator

### ISSUE THREAD

**Issue by andygill** [ku-fpg/remote-monad#9]
We need to test the performance of combinators working together. Things like `<*>` and `>>=` .

Specifically, I want to trigger this line, and figure out an efficient solution.

````
Appl f  <*> Bind m k = Bind (pure (,) <*> Appl f <*> m) (\ (a,b) -> pure a <*> k b)
````

**Comment by roboguy13** [comment]
I just added a benchmark that triggers that line and it does cause a non-linear increase in run time as the number of iterations goes up linearly. I also added a csv of that result in the `results` directory.

**Comment by andygill** [comment]
Thanks. I've brute-force fixed it with a new constructor in the (internal) remote monad.
